language: python
python:
  - "3.6"

dist: xenial

jdk:
  -oraclejdk8

env:
  global:
    - CC_TEST_REPORTER_ID=017785be117b3eae5746a7128bae39c21fdb4756cb32f7a29700c2eb884befca

install:
  - python -V
  - wget https://netix.dl.sourceforge.net/project/sdcc/sdcc-linux-amd64/3.8.0/sdcc-3.8.0-amd64-unknown-linux2.5.tar.bz2
  - tar xjf sdcc-3.8.0-amd64-unknown-linux2.5.tar.bz2
  - pushd sdcc-3.8.0 && sudo cp -r * /usr/local && popd && sdcc -v
  - git clone -q --depth 1 https://github.com/fayoh/stm8s-util.git
  - pushd stm8s-util && sudo make PREFIX=/usr/local/share/sdcc install && popd
  - pip install poetry
  - poetry -V

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make

after_script:
  - make test
  - pushd client/python
  - poetry run ../../cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - popd
  - sonar-scanner

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: PaMRS4a9ADP7XCj2PH00MjaX+RnNrzYZvGivABNmtimWmlEZ1gzQZ2flcXQTUBAW3gzWHkxzQB3u9DH5MzFL7qvrBan/MtZvniW0rGfgA09lH0Dw8FVA4CjTV4f3YuRBjGsqH95T9zfU2S0AEZR7WZef72sBFI7cJH27zOAFBdE7W9eKiEfqPuqIpp8hNTppVsSdL5ocfnFSvTx1zkXGb/ESfUTnt55Adnt93c1LzexD6spHLi3jfTCnd3ZYdEUJWF6Ii3espWHwIT54eQ7g+go/PkQssmzu5VBEzXptIOsS3+k6lu6ZwkC8g+TJf317TfxroZpmVctnrpVXwdIaudzsObgqjcX+7wh6Ynemf0CfY+WXHM2xvUd/HvBrD8sycAfj8MY3zys3t5oLe/gSZg/7yLjxNxvy5WGRPxxtQ+xokSQ0CAZCEP8jRLIvM2aoAbVBQvpefCfI1l9A6G9LA8q3PlEJ5N/eGyF6/K3ByytjvC59b8JGFk73JNeWv+EqFNiKkl4XsKYITgdQZJPMK+I5d4PQSXXKo3YmBKtnNfnGuv3KsGG0ghceAQCnxmL/bDFBiuXSqJp3JuL2N5iwWmb8d9GMAmftMNAUqNgW1BYPLAytkwyhVBnIrVLu+fOTMHOcF16v8m/rBtfICwacJ8arUKYScrOg1xydyTJCnXo=
  file: status_light.hex
  on:
    tags: true
    repo: fayoh/status_light

addons:
  sonarcloud:
    organization: "fayoh-github"
    token:
      secure: "nnnc2gtacjKwyNwNnYI2AVVdO+WOb2MoFklroa2Ycwa7FtxesnuArO01XTpcfwqJJa2DP5P4PeiWlcYYaz1C5Bo5EyA0gjHeWP32PaO4dXxfihr/sxLNU1chCPFiaGCLw79RCei5JVpe9WB2e/w9ZYakmcKS7Rz3UwVnAMG+tI43k5JZwe+sZH0cIPKq9feB63l+zO39TDYOHkcZJSviFblpP6jOF4RidJrgd+iylfOVrr7bH2qsqMA8LXIz/++FNXqZv3hSxRwIDLHEj642s6xkydLhmwedypEz3xwuu4B4jU3tJipXSPOdbomsSK1yMirzX5VwXmP8lpo/N9auBJAvYhx4cG3x+fFIqP6zs/OIasNtfYsFTOiRotlIQBSRr5qxVEGEo1x04Dd3OknwV3/7h+pwn+HYmhzkOJqCThIbpfxjKhUuf0ag/007gPflFBgPEwTlTTDVzF4p/cduuyJmMrKN0VGKJ75ZeFl9ZGIOK20cc/kdd+dZTLHKLn0M4n23rkINS+eMQcMVAO0ICBUbH1ZSB5bWBG1BoglSf5MMCf1XyCB7QWsbcwsEG59c1k9k9vwQju+dPY60rMImGW6kfPd1dqCmNLVXuYqkJ5wYCPxg6jEGgIIpGTKeo8RUrSpVZUiA0plRdbjKYRjOpQY/T2rL3i9paPbyPri1mzY="
      
