language: c

install:
  - wget https://netix.dl.sourceforge.net/project/sdcc/sdcc-linux-amd64/3.8.0/sdcc-3.8.0-amd64-unknown-linux2.5.tar.bz2
  - tar xjf sdcc-3.8.0-amd64-unknown-linux2.5.tar.bz2
  - pushd sdcc-3.8.0 && sudo cp -r * /usr/local && popd && sdcc -v
  - git clone -q --depth 1 https://github.com/fayoh/stm8s-util.git
  - pushd stm8s-util && sudo make install && popd

script: make
