language: c
dist: xenial
install:
- wget https://netix.dl.sourceforge.net/project/sdcc/sdcc-linux-amd64/3.8.0/sdcc-3.8.0-amd64-unknown-linux2.5.tar.bz2
- tar xjf sdcc-3.8.0-amd64-unknown-linux2.5.tar.bz2
- pushd sdcc-3.8.0 && sudo cp -r * /usr/local && popd && sdcc -v
- git clone -q --depth 1 https://github.com/fayoh/stm8s-util.git
- pushd stm8s-util && sudo make PREFIX=/usr/local/share/sdcc install && popd
script: make
deploy:
  provider: releases
  api_key:
    secure: pWwgCiUF+j16aW1MIc2/FpafZmc2AzXetvWEzimcgMHF/AK1kmkKcj+IdPmrgbhgd/Z4xtdncSc+dfUX6Sxx+BEuFTbJtuV1b9yMahAyMLFrK/7q5NxlODiJB9SmDR82veMATAs8MLFhXlGycyBlDDHfNsoF2gWbkhJRNsb+QzuHVsKXXYL1Yh9yRGV/RMiucQn28BechhCLsojC9fWxKtcs3eRrgMgcH3bOgwupMiGDSehcs3ucpEvr9aVlcMR/jx3AFM77/UdTbwNFKJQl8J2MYZMvwaIUwgxym5eC5HVtzHyyr4f/EYDIS/zn45t+WsQ7qeybjqD/verf932ykA/dOGslCg9dhYWVfcyLFQqorDJ8y90SLykqENkMD4TtKFc56aTofmZA3dm3ueRRSIIGoAN8Nh85MkSKb/C0wrKqMA3EetD6YLvcJT1N4IwPpwyI8UYb2O5LjjMYg4VJ8MsXM/GXrv1s9b5Enj1/PwfRdqe9qpBxs7Q4HP8gt7d9hbAWwjOGnlLDP2LCERym/fweKv4aBN6hFnDrDV/iw98Oy5PaYx0dlo52w0jOClG8jUOVhyRTAf4s1a8XfeOEWooWA0kkgMzFlfeXmPuxgNJOL2ls6sJRML0bMPGTmVhgaBym3S3Sjr3rcNygjg6E0E4hi1RKq8JlltvAAhC5oWQ=
  file: status_light.hex
  on:
    repo: fayoh/status_light
